name: Sqruff Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository code
        uses: actions/checkout@v3

      - name: Set up Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Install sqruff from GitHub
        run: cargo +nightly install --git https://github.com/gvozdvmozgu/sqruff.git --branch github-annotation-native

      - name: Run sqruff lint
        run: $HOME/.cargo/bin/sqruff lint --format github-annotation-native
